<a href="https://colab.research.google.com/github/rajmishra-dev/ML-Learning-project/blob/main/ab-test/ml_ad_testing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing a Libray.!

In [ ]:
import pandas as pd
import numpy as np
import random
import matplotlib.pyplot as plt
%matplotlib inline
random.seed(55)

In [ ]:
df = pd.read_csv('/content/ab_data.csv')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 252432 entries, 0 to 252431
Data columns (total 5 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   user_id       252432 non-null  int64
 1   timestamp     252432 non-null  object
 2   group         252432 non-null  object
 3   landing_page  252432 non-null  object
 4   converted     252431 non-null  float64
dtypes: float64(1), int64(1), object(3)
memory usage: 9.6+ MB

In [ ]:
df.head()

   user_id                   timestamp      group landing_page  converted
0   851104  2017-01-21 22:11:48.556739    control     old_page        0.0
1   804228  2017-01-12 08:01:45.159739    control     old_page        0.0
2   661590  2017-01-11 16:55:06.154213  treatment     new_page        0.0
3   853541  2017-01-08 18:28:03.143765  treatment     new_page        0.0
4   864975  2017-01-21 01:52:26.210827    control     old_page        1.0

In [ ]:
df.groupby(['group','converted']).agg('count')

                     user_id  timestamp  landing_page
group     converted
control   0.0         110911     110911        110911
          1.0          15246      15246         15246
treatment 0.0         111255     111255        111255
          1.0          15019      15019         15019

In [ ]:
df.drop(df.query("group == 'control' and landing_page == 'new_page'").index, inplace=True)
df.drop(df.query("group == 'treatment' and landing_page == 'old_page'").index, inplace=True)

df.groupby(['group','converted']).agg('count')

                     user_id  timestamp  landing_page
group     converted
control   0.0         109479     109479        109479
          1.0          15045      15045         15045
treatment 0.0         109771     109771        109771
          1.0          14808      14808         14808

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 249104 entries, 0 to 252431
Data columns (total 5 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   user_id       249104 non-null  int64
 1   timestamp     249104 non-null  object
 2   group         249104 non-null  object
 3   landing_page  249104 non-null  object
 4   converted     249103 non-null  float64
dtypes: float64(1), int64(1), object(3)
memory usage: 11.4+ MB

###Cleaning Duplicated Users

In [ ]:
df[df.duplicated(['user_id'], keep=False)]

      user_id                   timestamp      group landing_page  converted
1899   773192  2017-01-09 05:37:58.781806  treatment     new_page        0.0
2893   773192  2017-01-14 02:55:59.590927  treatment     new_page        0.0

In [ ]:
df.drop_duplicates(['user_id'], inplace=True)

In [ ]:
assert len(df['user_id'].unique()) == df['user_id'].size

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 249103 entries, 0 to 252431
Data columns (total 5 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   user_id       249103 non-null  int64
 1   timestamp     249103 non-null  object
 2   group         249103 non-null  object
 3   landing_page  249103 non-null  object
 4   converted     249102 non-null  float64
dtypes: float64(1), int64(1), object(3)
memory usage: 11.4+ MB

In [ ]:
df['converted'].mean()

np.float64(0.11984247416720861)

In [ ]:
df.groupby(['group']).describe()

            user_id                                                    \
              count           mean           std       min        25%
group
control    124525.0  788232.660237  91217.010201  630002.0  709429.00
treatment  124578.0  787687.820610  91137.706941  630000.0  708598.25

                                         converted                           \
                50%        75%       max     count      mean       std  min
group
control    788232.0  867140.00  945998.0  124524.0  0.120820  0.325919  0.0
treatment  787626.5  866520.25  945999.0  124578.0  0.118865  0.323631  0.0


           25%  50%  75%  max
group
control    0.0  0.0  0.0  1.0
treatment  0.0  0.0  0.0  1.0

In [ ]:
df.groupby(['group']).agg({'converted' : ['sum', 'count', 'mean']})

          converted
                sum   count      mean
group
control     15045.0  124524  0.120820
treatment   14808.0  124578  0.118865

In [ ]:
df.groupby(['group']).agg({'converted' : ['sum', 'count', 'mean']})

          converted
                sum   count      mean
group
control     15045.0  124524  0.120820
treatment   14808.0  124578  0.118865

In [ ]:
df[['group','converted']].groupby(['group']).agg('mean').T

group      control  treatment
converted  0.12082   0.118865